add ht-6
ASergeevi4/hillel_ht pull request #5
Opened 2022-02-20 12:02 UTC by ASergeevi4

Please check my 6th hometask (homework)

2022-02-20 12:09 UTC, fo0lman requested changes

2022-02-20 12:09 UTC, fo0lman commented on ht-6/index.html
> +                    <button> <a href="https://vivat-ukraine.com/kuler-dlya-vody-aquaworld-hc-66l-black-kompressornoe-ohlazhdenie-1/">Купить</a></button>
Нету смысла оборачивать а в button

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +.products .container {
Это нужно сделать как общий класс, который не должен принадлежать продуктам

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +.products .container .title {
убрать везде контейнер

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +.products .container .title {
из селекторов

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +    margin: 40px auto 20px;
зачем auto тут?
text-align не поможет?

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +    opacity: 60%;
лучше это переместить в color

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +    font-weight: bold;
лучше использовать значения 100-900

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +    font-weight: normal;
этот стиль по умолчанию normal

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +    opacity: .6;
также лучше задать через цвет

2022-02-20 12:09 UTC, fo0lman commented on ht-6/style.css
> +}
в таком случае не нужно было оборачивать img в div

2022-02-22 09:46 UTC, fo0lman requested changes

2022-02-22 09:46 UTC, fo0lman commented on ht-6/index.html
> +                    </div>
зачем оборачивать в logo если ты ему делаешь inline block? img и так inline

2022-02-22 09:46 UTC, fo0lman commented on ht-6/index.html
> +                    </div>
нужно или тут убрать logo или убрать у него стиль inline block

2022-02-22 09:46 UTC, fo0lman commented on ht-6/style.css
> +    font-weight: normal;
не нужно их задавать они и так по умолчанию в этих значениях

2022-02-22 15:28 UTC, ASergeevi4 commented on ht-6/index.html
> +                    </div>
Убрал inline block, но оставил класс logo

2022-02-22 15:28 UTC, ASergeevi4 commented on ht-6/style.css
> +    font-weight: normal;
Убрал эти стили. 
Ну и в конце добавил пустую строку в html

2022-02-23 08:17 UTC, fo0lman approved these changes

2022-02-23 08:17 UTC, merged